language: generic
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: >
        TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: >
        TARGET=x86_64-unknown-linux-musl
        MUSL=x86_64-linux-musl
    - os: linux
      env: >
        TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
    - os: linux
      env: >
        TARGET=i686-unknown-linux-musl
        MUSL=x86_64-x32-linux-musl
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
    - os: linux
      env: >
        TARGET=armv7-unknown-linux-gnueabihf
        SKIP_TESTS=1
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - gcc-4.8-multilib-arm-linux-gnueabihf
            - g++-arm-linux-gnueabihf
            - g++-4.8-multilib-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - libstdc++6-armhf-cross
            # For building snapshots, a 32-bit host compiler is needed
            - gcc-multilib
            - g++-multilib
    - os: linux
      env: >
        TARGET=armv7-unknown-linux-musleabihf
        MUSL=arm-linux-musleabihf
        SKIP_TESTS=1
      addons:
        apt:
          packages:
            # For building snapshots, a 32-bit host compiler is needed
            - gcc-multilib
            - g++-multilib
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=x86_64-apple-darwin
    - os: osx
      osx_image: xcode8
      env: >
        TARGET=i686-apple-darwin

env:
  global:
    - V8_LIBS=$TRAVIS_BUILD_DIR/v8-build/lib/libv8uber.a
    - V8_SOURCE=$TRAVIS_BUILD_DIR/v8-build

addons:
  apt:
    packages:
      # Coverage deps
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

install:
  - if [ -n "$MUSL" ]; then export PATH="$PWD/musl/bin:$PATH"; fi
  - export PATH="$HOME/.cargo/bin:$PATH"
  - ./ci install

script: ./ci test

after_success: ./ci coverage

before_deploy: ./ci deploy

deploy:
  - provider: script
    script: ./ci deploy-gh-pages
    skip_cleanup: true
    on:
      repo: dflemstr/rq
  - provider: s3
    access_key_id: AKIAIMXXFE4ETRSISAEA
    secret_access_key:
      secure: "BwXmKjyKJVzmBp9GyJ0raBrJP1cHZ8LYyUxIlHzhb7Zfxlot/R5HwnNKqYlu6QJb0VBL+vcFjzujHljvlPSu/fLFlg4MNc36l3IeowOchvZpv+2+72IgJCJgxC+d7s0Al/TILB4htYVwoIAAvO99HerKKX91M2TeCyEoYIK1PmYjw6c0gZo5CifUe9EISFqIzuUGysZsZFCsHF0purhIAIWBBJjgu35XLluvu+kZ1bJ22Fqvsz2x1MUyyNHV4pNw6gYwC4CSBwACuu2aQDY7i+ZXU6ubSyK5P495rElWqMpMtMVg0oxH+UAsdw4La2DwxkF8dc/4w4eYaix7ucXrV1n24M34nzm4GwZ3/n4ZANaRAtl6zxhTPk5UadEX5PAOAxPsTPDJYQPSU/ZkbdUsYm6YhJtw/HDQOAkwhrZs2PibVyM6JB34/AsJrryl+yZ+By7M2AOnDcLWAvYroqFVW316yIe1x4EJW9loknqNCseDGEHCqtAjX5tFB3n7h8w+p2VpoaR23AM1BoOUEuWzfQZtCULKSZFwFDlj3pnJAdC2zqojtr87zNcqUX+XMy7YpoLEVGetG8zpAYmKXE8r7jNrSMOagBph90ThN+D9Zjkku5p9xH2Xw2kRhZdY56JrhJApotWJ8j3Gr6dt8rRAssa8E388Xz+EMAC34fo2tr8="
    bucket: record-query
    region: eu-west-1
    skip_cleanup: true
    local_dir: target/deploy
    upload-dir: record-query
    on:
      repo: dflemstr/rq
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "target/deploy-release/*"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
